from classes.input import Input

if __name__ == "__main__":
    app = Input()
    app.run()

#--- foco
# os erros aparentemente estão OK

# TODO TEM QUE VER A QUESTÃO DOS DIAS CORRIDOS E DIAS ÚTEIS
# TODO CHECAR QUESTÕES DOS VALORES NEGATIVOS
# TODO MULTIPLICAR TAXA MÉDIA POR 100
# TODO VER FUNDO SOBERANO NO CALCULO DO CAIXAPL, ajeitar o CVNP

# TODO ADICIONAR OUTROS FIDCs(rnx, sabia, ioxI), IOSAN = IOXI
# TODO FAZER ESCOLHER ENTRE PEGAR O MAIS ATUALIZADO E O DO MÊS EXATO
# TODO AJEITAR TUDO RELACIONADO A COMPARAÇÃO DAS COLUNAS.YAML PARA FAZER O STRIP SEMPRE

# AQUI É ACHAR ERROS E TRATAR O MÁXIMO DE TODOS PRA SEMPRE TER ALGUM DIAGNOSTICO