from classes.entry import Entry

if __name__ == "__main__":
    app = Entry()
    app.run()

# TODO TEM QUE VER A QUESTÃO DOS DIAS CORRIDOS E DIAS ÚTEIS
# TODO CHECAR QUESTÕES DOS VALORES NEGATIVOS
# TODO CRIAR AS COLUNAS QUE PEDIRAM

# TODO DETECTAR ERRO DO ITEM FALTANTE
# TODO ERRO CASO TENHA QUANTIDADES DE SHEETS DIFERENTES DO ESPERADO

# TODO VER FUNDO SOBERANO NO CALCULO DO CAIXAPL
# TODO AJEITAR FIRMA, RNX, SABIA E AFINS
# TODO AJEITAR O STREAMLIT E AFINS (erro desconhecido)

# TODO AJEITAR QUE APAGA OS DADOS DEPOIS QUE FECHAR TUDO (BOTÃO DE FECHAR)

#--- foco
# TODO resolver questão redundante no exceltransformer dos paths, deixar tudo padronizado
# TODO download tá bugado ajeitar

# AQUI É ACHAR ERROS E TRATAR O MÁXIMO DE TODOS PRA SEMPRE TER ALGUM DIAGNOSTICO